#ifndef UGAMEENGINE_GLOBAL_H
#define UGAMEENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UGAMEENGINE_LIBRARY)
#  define UGAMEENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define UGAMEENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UGAMEENGINE_GLOBAL_H
